// Serverless endpoint untuk menyimpan analytics ke Supabase (server-side)
//
// Langkah konfigurasi di Vercel:
// 1. Di project Vercel ini, buka Settings → Environment Variables
// 2. Tambah:
//    - SUPABASE_URL       = https://YOUR_PROJECT_REF.supabase.co
//    - SUPABASE_ANON_KEY  = sb_publishable_... (key yang kamu kirim)
// 3. Deploy ulang project.
//
// Di Supabase, buat table (SQL di "Table: analytics_events" di bawah).

// Default Supabase config (boleh di-overwrite via env di Vercel)
const DEFAULT_SUPABASE_URL = 'https://srxjfxpfcwyongqyewis.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyeGpmeHBmY3d5b25ncXlld2lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4ODU1ODksImV4cCI6MjA4NjQ2MTU4OX0.baa4l-1Is1qIVN7PBQHWw5uVf5fe4jaPcIe4n6eCGJs';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const SUPABASE_URL = process.env.SUPABASE_URL || DEFAULT_SUPABASE_URL;
  const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || DEFAULT_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    return res.status(500).json({ error: 'Supabase env not configured' });
  }

  try {
    const { type, path, personaId, meta } = req.body || {};

    const ip =
      (req.headers['x-forwarded-for'] || '')
        .toString()
        .split(',')[0]
        .trim() || null;
    const country = req.headers['x-vercel-ip-country'] || null;
    const city = req.headers['x-vercel-ip-city'] || null;
    const userAgent = req.headers['user-agent'] || null;

    const payload = {
      type: type || null,
      path: path || null,
      persona_id: personaId ?? null,
      meta: meta || null,
      ip,
      country,
      city,
      user_agent: userAgent,
    };

    const resp = await fetch(`${SUPABASE_URL}/rest/v1/analytics_events`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
        Prefer: 'return=minimal',
      },
      body: JSON.stringify(payload),
    });

    if (!resp.ok) {
      const text = await resp.text();
      return res.status(500).json({ error: 'Supabase insert failed', detail: text });
    }

    return res.status(200).json({ ok: true });
  } catch (err) {
    return res.status(500).json({ error: 'Unexpected error', detail: String(err) });
  }
}

/*
Table: analytics_events (buat di Supabase SQL editor)

create table if not exists public.analytics_events (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  type        text,
  path        text,
  persona_id  int,
  meta        jsonb,
  ip          text,
  country     text,
  city        text,
  user_agent  text
);

-- Row Level Security boleh dinyalakan, tapi izinkan insert dari anon key:
alter table public.analytics_events enable row level security;

create policy "Allow insert from anon" on public.analytics_events
  for insert
  to anon
  with check (true);
*/

